/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import dominios.Computador;
import dominios.Funcionario;
import funcionamento.sistema.GeradorDeLog;
import java.awt.Image;
import javax.imageio.ImageIO;
import model.dao.ComputadorDao;

/**
 *
 * @author Victor
 */
public class HostFuncionario extends javax.swing.JFrame {

    private MeuPC telaMeuPC;
    private Relatos telaRelatos;
    private App telaLogin;
    private MeuSmy telaMeuSmy;
    private ComputadorDao computadorDao = new ComputadorDao();
    private Funcionario funcionarioUtilizando = new Funcionario();
    private GeradorDeLog geradorDeLog = new GeradorDeLog();
    

    /**
     * Creates new form HostFuncionario
     */
    public HostFuncionario() {
        initComponents();
        trocarIconeDaJanela();
    }

    public HostFuncionario(Computador computador, Funcionario funcionarioLogado) {
        initComponents();
        trocarIconeDaJanela();
        funcionarioUtilizando.setIdFuncionario(funcionarioLogado.getIdFuncionario());
        funcionarioUtilizando.setNomeFuncionario(funcionarioLogado.getNomeFuncionario());
        funcionarioUtilizando.setLoginFuncionario(funcionarioLogado.getLoginFuncionario());
        funcionarioUtilizando.setSenhaFuncionario(funcionarioLogado.getSenhaFuncionario());
        funcionarioUtilizando.setEmailFuncionario(funcionarioLogado.getEmailFuncionario());
        funcionarioUtilizando.setTelefoneFuncionario(funcionarioLogado.getTelefoneFuncionario());
        if (funcionarioLogado.getPermissaoAdmin().equals("Administrador")) {
            funcionarioUtilizando.setPermissaoAdmin(1);
        } else {
            funcionarioUtilizando.setPermissaoAdmin(0);
        }
        funcionarioUtilizando.setEmpresa(funcionarioLogado.getEmpresa());
        funcionarioUtilizando.setTipoFuncionario(funcionarioLogado.getTipoFuncionario());
        telaRelatos = new Relatos(funcionarioLogado);
        telaRelatos.setVisible(false);
        pnlVisivel.add(telaRelatos);
        String nomeFuncionario = funcionarioLogado.getNomeFuncionario();
        lblValorNomeFuncionario.setText(nomeFuncionario.toUpperCase());
        telaMeuPC = new MeuPC(computador, funcionarioLogado);
        pnlVisivel.add(telaMeuPC);
        telaMeuPC.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        imgIconeAzul = new javax.swing.JLabel();
        imgIconePerfil = new javax.swing.JLabel();
        lblTituloBemVindo = new javax.swing.JLabel();
        lblValorNomeFuncionario = new javax.swing.JLabel();
        imgIconeDash = new javax.swing.JLabel();
        imgIconeMensagem = new javax.swing.JLabel();
        imgIconeSmy = new javax.swing.JLabel();
        lblTituloMeuPC = new javax.swing.JLabel();
        lblTituloRelatos = new javax.swing.JLabel();
        lblTituloMeuSmy = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        pnlVisivel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1152, 700));
        setMaximumSize(new java.awt.Dimension(1152, 700));
        setMinimumSize(new java.awt.Dimension(1152, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1152, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1152, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1152, 700));

        jPanel2.setBackground(new java.awt.Color(47, 104, 166));
        jPanel2.setMaximumSize(new java.awt.Dimension(268, 700));
        jPanel2.setMinimumSize(new java.awt.Dimension(268, 700));
        jPanel2.setPreferredSize(new java.awt.Dimension(268, 700));

        imgIconeAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoAzul.png"))); // NOI18N

        imgIconePerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconePerfilBranco.png"))); // NOI18N

        lblTituloBemVindo.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lblTituloBemVindo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloBemVindo.setText("SEJA BEM VINDO");

        lblValorNomeFuncionario.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lblValorNomeFuncionario.setForeground(new java.awt.Color(115, 202, 246));
        lblValorNomeFuncionario.setText("[FUNCIONÁRIO]");

        imgIconeDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeDashRosa.png"))); // NOI18N
        imgIconeDash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imgIconeMensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeMensagemBranca.png"))); // NOI18N
        imgIconeMensagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imgIconeSmy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeSmyBranco.png"))); // NOI18N
        imgIconeSmy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblTituloMeuPC.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblTituloMeuPC.setForeground(new java.awt.Color(255, 213, 233));
        lblTituloMeuPC.setText("MEU PC");
        lblTituloMeuPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTituloMeuPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloMeuPCMouseClicked(evt);
            }
        });

        lblTituloRelatos.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblTituloRelatos.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRelatos.setText("RELATOS");
        lblTituloRelatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTituloRelatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloRelatosMouseClicked(evt);
            }
        });

        lblTituloMeuSmy.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblTituloMeuSmy.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloMeuSmy.setText("MEU SMY");
        lblTituloMeuSmy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTituloMeuSmy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloMeuSmyMouseClicked(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(47, 104, 166));
        btnLogout.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.setToolTipText("");
        btnLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(115, 202, 246), 1, true));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setMaximumSize(new java.awt.Dimension(148, 52));
        btnLogout.setMinimumSize(new java.awt.Dimension(148, 52));
        btnLogout.setPreferredSize(new java.awt.Dimension(148, 52));
        btnLogout.setVerifyInputWhenFocusTarget(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imgIconeDash)
                                    .addComponent(imgIconeMensagem)
                                    .addComponent(imgIconeSmy))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTituloRelatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTituloMeuPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTituloMeuSmy, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(imgIconePerfil)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTituloBemVindo)
                                    .addComponent(lblValorNomeFuncionario)))
                            .addComponent(imgIconeAzul))
                        .addGap(32, 32, 32))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblValorNomeFuncionario)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(imgIconeAzul)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(imgIconePerfil))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lblTituloBemVindo)))))
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblTituloMeuPC)
                    .addComponent(imgIconeDash))
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgIconeMensagem)
                    .addComponent(lblTituloRelatos))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblTituloMeuSmy)
                    .addComponent(imgIconeSmy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        lblTituloBemVindo.getAccessibleContext().setAccessibleDescription("");

        pnlVisivel.setBackground(new java.awt.Color(255, 255, 255));
        pnlVisivel.setForeground(new java.awt.Color(255, 255, 255));
        pnlVisivel.setMaximumSize(new java.awt.Dimension(933, 700));
        pnlVisivel.setMinimumSize(new java.awt.Dimension(933, 700));

        javax.swing.GroupLayout pnlVisivelLayout = new javax.swing.GroupLayout(pnlVisivel);
        pnlVisivel.setLayout(pnlVisivelLayout);
        pnlVisivelLayout.setHorizontalGroup(
            pnlVisivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
        );
        pnlVisivelLayout.setVerticalGroup(
            pnlVisivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlVisivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlVisivel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblTituloMeuPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloMeuPCMouseClicked
        // Quando clicar, vai trocar as cores dos ícones (estou mudando a imagem para fazer isso)
        imgIconeDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeDashRosa.png"))); // NOI18N
        imgIconeMensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeMensagemBranca.png"))); // NOI18N
        imgIconeSmy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeSmyBranco.png"))); // NOI18N

        // Quando clicar, vai trocar as cores dos textos
        lblTituloMeuPC.setForeground(new java.awt.Color(255, 213, 233));
        lblTituloRelatos.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloMeuSmy.setForeground(new java.awt.Color(255, 255, 255));

        // Aqui vai fazer a navegação entre as telas
        telaMeuPC.setVisible(true);
        telaRelatos.setVisible(false);
        try {
            telaMeuSmy.setVisible(false);
        } catch (NullPointerException e) {
        }
    }//GEN-LAST:event_lblTituloMeuPCMouseClicked

    private void lblTituloRelatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloRelatosMouseClicked
        // Quando clicar, vai trocar as cores dos ícones (estou mudando a imagem para fazer isso)
        imgIconeDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeDashBranco.png")));
        imgIconeMensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeMensagemRosa.png")));
        imgIconeSmy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeSmyBranco.png")));

        // Quando clicar, vai trocar as cores dos textos
        lblTituloMeuPC.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRelatos.setForeground(new java.awt.Color(255, 213, 233));
        lblTituloMeuSmy.setForeground(new java.awt.Color(255, 255, 255));

        // Aqui vai fazer a navegação entre as telas
        telaMeuPC.setVisible(false);
        telaRelatos.setVisible(true);
        try {
            telaMeuSmy.setVisible(false);
        } catch (NullPointerException e) {
        }
    }//GEN-LAST:event_lblTituloRelatosMouseClicked

    private void lblTituloMeuSmyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloMeuSmyMouseClicked
        // Quando clicar, vai trocar as cores dos ícones (estou mudando a imagem para fazer isso)
        imgIconeDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeDashBranco.png")));
        imgIconeMensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeMensagemBranca.png")));
        imgIconeSmy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeSmyRosa.png")));

        // Quando clicar, vai trocar as cores dos textos
        lblTituloMeuPC.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRelatos.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloMeuSmy.setForeground(new java.awt.Color(255, 213, 233));

        // Aqui vai criar uma tela MeuSmy passando um funcionário como parâmetro
        telaMeuSmy = new MeuSmy(funcionarioUtilizando);
        pnlVisivel.add(telaMeuSmy);
        telaMeuSmy.setVisible(true);

        // Aqui vai fazer a navegação entre as telas
        telaMeuPC.setVisible(false);
        telaRelatos.setVisible(false);
//        telaMeuSmy.setVisible(true);
    }//GEN-LAST:event_lblTituloMeuSmyMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        App telaLogin = new App();
        telaLogin.setVisible(true);
        telaMeuPC.setMonitorar(false);
        telaMeuPC.getNovaThread().interrupt();
        geradorDeLog.adicionarLog("INFO", "Monitoramento do computador " + geradorDeLog.getSerialPC() + " do funcionário " + funcionarioUtilizando.getNomeFuncionario() + " pausado");
        geradorDeLog.adicionarLog("INFO", "Funcionário " + funcionarioUtilizando.getNomeFuncionario() + " realizou logout da aplicação");
        this.dispose();

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void trocarIconeDaJanela() {
        Image im = null;
        try {
            im = ImageIO.read(getClass().getResource("/imagens/smyGrande.png"));
        } catch (Exception e) {
            System.out.println(e);;
        }
        setIconImage(im);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HostFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HostFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HostFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HostFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HostFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel imgIconeAzul;
    private javax.swing.JLabel imgIconeDash;
    private javax.swing.JLabel imgIconeMensagem;
    private javax.swing.JLabel imgIconePerfil;
    private javax.swing.JLabel imgIconeSmy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTituloBemVindo;
    private javax.swing.JLabel lblTituloMeuPC;
    private javax.swing.JLabel lblTituloMeuSmy;
    private javax.swing.JLabel lblTituloRelatos;
    private javax.swing.JLabel lblValorNomeFuncionario;
    private javax.swing.JDesktopPane pnlVisivel;
    // End of variables declaration//GEN-END:variables
}
