/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import conexao.ConexaoSmy;
import dominios.Funcionario;
import dominios.Relato;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Victor
 */
public class MeuSmy extends javax.swing.JInternalFrame {

    private Funcionario funcionario = new Funcionario();
    private List<String> listaDeDicasFeliz = new ArrayList();
    private List<String> listaDeDicasNeutro = new ArrayList();
    private List<String> listaDeDicasTriste = new ArrayList();
    private List<String> listaDeMensagens = new ArrayList();
    private Integer contadorDeRelatos = 0;

    /**
     * Creates new form MeuSmy
     */
    public MeuSmy() {
        initComponents();
    }

    public MeuSmy(Funcionario funcionarioLogado) {
        initComponents();
        funcionario.setIdFuncionario(funcionarioLogado.getIdFuncionario());
        funcionario.setNomeFuncionario(funcionarioLogado.getNomeFuncionario());
        funcionario.setLoginFuncionario(funcionarioLogado.getLoginFuncionario());
        funcionario.setSenhaFuncionario(funcionarioLogado.getSenhaFuncionario());
        funcionario.setEmailFuncionario(funcionarioLogado.getEmailFuncionario());
        funcionario.setTelefoneFuncionario(funcionarioLogado.getTelefoneFuncionario());
        if (funcionarioLogado.getPermissaoAdmin().equals("Administrador")) {
            funcionario.setPermissaoAdmin(1);
        } else {
            funcionario.setPermissaoAdmin(0);
        }
        funcionario.setEmpresa(funcionarioLogado.getEmpresa());
        funcionario.setTipoFuncionario(funcionarioLogado.getTipoFuncionario());
        populaListaDeMensagens();
        populaListaDeDicasFeliz();
        populaListaDeDicasNeutro();
        populaListaDeDicasTriste();
        verificarRelato();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMeuSmy = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDica = new javax.swing.JTextArea();
        imgSmyGrande2 = new javax.swing.JLabel();
        imgBalaoFala1 = new javax.swing.JLabel();
        lblTituloEstadoSmy = new javax.swing.JLabel();
        lblValorEstado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblDica2 = new javax.swing.JLabel();
        lblDica3 = new javax.swing.JLabel();
        lblDica1 = new javax.swing.JLabel();
        topico3 = new javax.swing.JLabel();
        topico1 = new javax.swing.JLabel();
        topico2 = new javax.swing.JLabel();
        lblTituloMeuSmy = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(933, 700));
        setMinimumSize(new java.awt.Dimension(933, 700));
        setPreferredSize(new java.awt.Dimension(933, 700));

        pnlMeuSmy.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDica.setEditable(false);
        txtDica.setBackground(new java.awt.Color(230, 230, 230));
        txtDica.setColumns(20);
        txtDica.setFont(new java.awt.Font("Ebrima", 1, 22)); // NOI18N
        txtDica.setForeground(new java.awt.Color(67, 67, 67));
        txtDica.setLineWrap(true);
        txtDica.setRows(5);
        txtDica.setText("Por favor, realize o seu relato para que eu consiga te ajudar!");
        txtDica.setSelectedTextColor(new java.awt.Color(240, 240, 240));
        jScrollPane2.setViewportView(txtDica);
        jScrollPane2.setBorder(null);
        txtDica.setWrapStyleWord(true);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 470, 90));
        jScrollPane2.setVerticalScrollBarPolicy(jScrollPane2.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setHorizontalScrollBarPolicy(jScrollPane2.HORIZONTAL_SCROLLBAR_NEVER);

        imgSmyGrande2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/smyGrande.png"))); // NOI18N
        jPanel2.add(imgSmyGrande2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        imgBalaoFala1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balaoFala.png"))); // NOI18N
        jPanel2.add(imgBalaoFala1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -3, -1, 110));

        lblTituloEstadoSmy.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        lblTituloEstadoSmy.setForeground(new java.awt.Color(67, 67, 67));
        lblTituloEstadoSmy.setText("ESTADO");
        jPanel2.add(lblTituloEstadoSmy, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        lblValorEstado.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        lblValorEstado.setForeground(new java.awt.Color(67, 67, 67));
        lblValorEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorEstado.setText("Sem recomendações");
        lblValorEstado.setMaximumSize(new java.awt.Dimension(170, 25));
        lblValorEstado.setMinimumSize(new java.awt.Dimension(170, 25));
        lblValorEstado.setPreferredSize(new java.awt.Dimension(170, 25));
        jPanel2.add(lblValorEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, -1));

        jPanel1.setBackground(new java.awt.Color(213, 239, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDica2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lblDica2.setForeground(new java.awt.Color(67, 67, 67));
        lblDica2.setMaximumSize(new java.awt.Dimension(372, 60));
        lblDica2.setMinimumSize(new java.awt.Dimension(372, 60));
        lblDica2.setName(""); // NOI18N
        lblDica2.setPreferredSize(new java.awt.Dimension(372, 60));
        jPanel1.add(lblDica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        lblDica3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lblDica3.setForeground(new java.awt.Color(67, 67, 67));
        lblDica3.setText("                                 ");
        lblDica3.setMaximumSize(new java.awt.Dimension(372, 60));
        lblDica3.setMinimumSize(new java.awt.Dimension(372, 60));
        lblDica3.setPreferredSize(new java.awt.Dimension(372, 60));
        jPanel1.add(lblDica3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        lblDica1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lblDica1.setForeground(new java.awt.Color(67, 67, 67));
        lblDica1.setText("                                ");
        lblDica1.setMaximumSize(new java.awt.Dimension(372, 60));
        lblDica1.setMinimumSize(new java.awt.Dimension(372, 60));
        lblDica1.setPreferredSize(new java.awt.Dimension(372, 60));
        jPanel1.add(lblDica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        topico3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/topico.png"))); // NOI18N
        jPanel1.add(topico3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        topico1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/topico.png"))); // NOI18N
        jPanel1.add(topico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        topico2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/topico.png"))); // NOI18N
        jPanel1.add(topico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 460, 220));

        lblTituloMeuSmy.setFont(new java.awt.Font("Ebrima", 1, 35)); // NOI18N
        lblTituloMeuSmy.setForeground(new java.awt.Color(67, 67, 67));
        lblTituloMeuSmy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloMeuSmy.setText("MEU SMY");

        javax.swing.GroupLayout pnlMeuSmyLayout = new javax.swing.GroupLayout(pnlMeuSmy);
        pnlMeuSmy.setLayout(pnlMeuSmyLayout);
        pnlMeuSmyLayout.setHorizontalGroup(
            pnlMeuSmyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeuSmyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addComponent(lblTituloMeuSmy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMeuSmyLayout.setVerticalGroup(
            pnlMeuSmyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMeuSmyLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTituloMeuSmy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMeuSmy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMeuSmy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void verificarRelato() {
        ConexaoSmy conexao = new ConexaoSmy();
        Connection con = conexao.conectar();
        PreparedStatement pstm;
        ResultSet resultadoSelect;
        List<Relato> listaDeRelatosFuncionario = new ArrayList();

        try {
            String verificarRelato = "SELECT momentoRelato, sentimento FROM relato where fkFuncionario = ?";
            pstm = con.prepareStatement(verificarRelato);
            pstm.setInt(1, funcionario.getIdFuncionario());
            resultadoSelect = pstm.executeQuery();

            while (resultadoSelect.next()) {
                listaDeRelatosFuncionario.add(new Relato(resultadoSelect.getString("sentimento"), (resultadoSelect.getDate("momentoRelato").toString()).substring(0, 10)));
            }

            for (Relato relatoFuncionario : listaDeRelatosFuncionario) {
                if (relatoFuncionario.getMomentoRelato().equals(consultarSomenteDataDeAgora())) {
                    lblValorEstado.setText(relatoFuncionario.getSentimento());
                    switch (relatoFuncionario.getSentimento()) {
                        case "Feliz": {
                            txtDica.setText(listaDeMensagens.get(0));
                            lblDica1.setText(listaDeDicasFeliz.get(0));
                            lblDica2.setText(listaDeDicasFeliz.get(1));
                            lblDica3.setText(listaDeDicasFeliz.get(2));
                            break;
                        }
                        case "Neutro": {
                            txtDica.setText(listaDeMensagens.get(1));
                            lblDica1.setText(listaDeDicasNeutro.get(0));
                            lblDica2.setText(listaDeDicasNeutro.get(1));
                            lblDica3.setText(listaDeDicasNeutro.get(2));
                            break;
                        }
                        case "Triste": {
                            txtDica.setText(listaDeMensagens.get(2));
                            lblDica1.setText(listaDeDicasTriste.get(0));
                            lblDica2.setText(listaDeDicasTriste.get(1));
                            lblDica3.setText(listaDeDicasTriste.get(2));
                            break;
                        }
                        default: {
                            break;
                        }
                    }
                }
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    public String consultarSomenteDataDeAgora() {
        Timestamp dataDeHoje = new Timestamp(System.currentTimeMillis());
        return (new SimpleDateFormat("yyyy-MM-dd").format(dataDeHoje));
    }

    public void populaListaDeMensagens() {
        listaDeMensagens.add("Vejo que você está feliz! Para manter este sentimento, recomendo:");
        listaDeMensagens.add("Seu dia está mais ou menos? Tente:");
        listaDeMensagens.add(String.format("Poxa %s, você está triste :( Quero muito te ajudar <3, então vou te dar algumas dicas:", funcionario.getNomeFuncionario()));
    }

    public void populaListaDeDicasFeliz() {
        listaDeDicasFeliz.add("<html>Compartilhar sua felicidade com o próximo</html>");
        listaDeDicasFeliz.add("<html>Lembrar de seus sonhos e objetivos e como tudo está caminhando bem para alcançá-los</html>");
        listaDeDicasFeliz.add("<html>Falar para pessoas próximas o quão importante são para você</html>");
    }

    public void populaListaDeDicasNeutro() {
        listaDeDicasNeutro.add("<html>Fazer/Pedir sua comida favorita!</html>");
        listaDeDicasNeutro.add("<html>Escutar músicas que você gosta</html>");
        listaDeDicasNeutro.add("<html>Fazer algo fora de sua rotina (cozinhar, fazer uma caminhada, jogar videogame, entre outros). Se permita experiências novas</html>");
    }

    public void populaListaDeDicasTriste() {
        listaDeDicasTriste.add("<html>Fazer o exercício de enxergar o lado positivo da sua situação atual</html>");
        listaDeDicasTriste.add("<html>Conversar com um amigo próximo sobre o que está sentindo, não guarde pra você. Se não tiver ninguém, há pessoas dispostas a conversar se ligar para 188</html>");
        listaDeDicasTriste.add("<html>Se a sua tristeza é recorrente e não passa, por favor, procurar uma ajuda profissional</html>");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgBalaoFala1;
    private javax.swing.JLabel imgSmyGrande2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDica1;
    private javax.swing.JLabel lblDica2;
    private javax.swing.JLabel lblDica3;
    private javax.swing.JLabel lblTituloEstadoSmy;
    private javax.swing.JLabel lblTituloMeuSmy;
    private javax.swing.JLabel lblValorEstado;
    private javax.swing.JPanel pnlMeuSmy;
    private javax.swing.JLabel topico1;
    private javax.swing.JLabel topico2;
    private javax.swing.JLabel topico3;
    private javax.swing.JTextArea txtDica;
    // End of variables declaration//GEN-END:variables
}
